//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Project.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseInfomation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HouseInfomation()
        {
            this.HouseRoomsMaps = new HashSet<HouseRoomsMap>();
            this.HouseTypesMaps = new HashSet<HouseTypesMap>();
        }
    
        public int Id { get; set; }
        public Nullable<int> HouseCategoryId { get; set; }
        public string HouseName { get; set; }
        public string HouseTitle { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public string YearEstablish { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public Nullable<int> Status { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<double> LocationLat { get; set; }
        public Nullable<double> LocationLng { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual HouseCategory HouseCategory { get; set; }
        public virtual HouseFeaturesMap HouseFeaturesMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseRoomsMap> HouseRoomsMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseTypesMap> HouseTypesMaps { get; set; }
    }
}
